# Generated by Django 5.0.1 on 2024-04-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_types_consumption_types_camunalca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtors',
            name='product',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
    ]
